name: CI
run-name: ${{ github.actor }} CI tests
#on: [push]
jobs:
    phpunit:
        runs-on: ubuntu-latest
        services:
        steps:
            - uses: actions/checkout@v4
            - name: Set up PHP
            - uses: shivammathur/setup-php@v4
              with:
                php-version: '8.3'
            - name: Install Dependencies
            - run: composer install --no-progress --no-suggest --prefer-dist
            - name: Prepare Application
            - run: cp .env.example .env
            - run: php artisan key:generate
            - name: Run Tests
            - run: vendor/bin/phpunit